package ai.moeru.airicraft.agent.tasks;

public enum EvidenceKind {
	INVENTORY_DELTA_AT_LEAST,
	ITEM_COUNT_AT_LEAST,
	ITEM_DELTA_AT_LEAST,
	STEP_COMPLETED,
	POSITION_REACHED,
	RECIPE_CRAFTED,
	ITEMS_TRANSFERRED,
	BLOCK_PLACED,
	MISSION_FINISHED
}
